# Generated by Django 2.0.7 on 2018-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(related_name='user_role', to='RBAC.Role', verbose_name='所属角色'),
        ),
    ]
