# Generated by Django 2.0.7 on 2018-07-16 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RBAC', '0002_profile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='申请邮箱')),
                ('urlarg', models.CharField(max_length=50, verbose_name='注册参数')),
                ('status', models.CharField(choices=[('0', '待审批'), ('1', '审批通过'), ('2', '审批拒绝')], default='0', max_length=50, verbose_name='审批状态')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否审批')),
                ('is_use', models.BooleanField(default=False, verbose_name='是否使用')),
                ('starttime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='审批时间')),
                ('action_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regist_for_actionuser', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrequest_area', to='RBAC.Area', verbose_name='所属区域')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequest_role', to='RBAC.Role', verbose_name='账号权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserResetpsd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='申请邮箱')),
                ('urlarg', models.CharField(max_length=50, verbose_name='重置参数')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否使用')),
                ('updatetime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
