# Generated by Django 2.0.7 on 2019-09-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0003_userrequest_userresetpsd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': '属地'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name_plural': '注册审批'},
        ),
    ]
